services:
  mongodb:
    image: 'mongo:latest'
    container_name: self-employed-acq-mongodb
    environment:
      - 'MONGO_INITDB_DATABASE=self-employed-acq'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
      - 'MONGO_INITDB_ROOT_USERNAME=self-employed-acq'
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
