FROM node:alpine AS builder
WORKDIR /app
COPY frontend/package.json ./
COPY frontend/yarn.lock ./
RUN yarn install --frozen-lockfile --network-timeout 100000
COPY frontend .
RUN echo "REACT_APP_ENV=PROD" > .env
RUN yarn build

FROM nginx:alpine AS server
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder ./app/build /usr/share/nginx/html
